### ISSUE TITLE
Value/form issues

### ISSUE THREAD

**Issue by chrzyki** [lexibank/beidasinitic#7]
I noticed a couple of small issues for the value/form output in CLDF:

- there are a number of `&quot;` strings in values and forms (also in the source material)
- there are a number of split values separated by `，` (i.e. full-width comma, unicode FF0C, not unicode 02 comma) where value == form for the CLDF output (e.g. uə²¹³，ə²¹³, tʰiəp⁴，tʰaʔ⁴, etc.)
- unicode 2777 (❷) appears in the source material and thus also in CLDF values/forms

**Comment by LinguList** [comment]
yep, but not in tokens, right?

**Comment by LinguList** [comment]
because, as far as this workflow goes, the SEGMENTS have been done way before lexibank times.

**Comment by chrzyki** [comment]
Correct, not in the tokens.

**Comment by LinguList** [comment]
The reason is that the data were provided in WORD by a digitization organization. Since we add forms explicitly, it is not that easy to clean them directly now, right? Or can we use the formspec to manipulate only the form?

**Comment by chrzyki** [comment]
One option I think would work is to use `FormSpec()` and explicitly call it and generate the forms as for example in `kitchensemitic`:

https://github.com/lexibank/kitchensemitic/blob/c8f2e53fab65dd21753e88f0140aec13a1a8b747/lexibank_kitchensemitic.py#L94-L97

```python
# Note that we cannot use the internal splitting algorithm, because of individual
# problems in the source data cells. Thus, we call form_spec explicitly.
forms = self.form_spec.split(item=None, value=lexeme)
cogs = self.form_spec.split(item=None, value=cogs)
```

**Comment by LinguList** [comment]
Yes, sounds like a good idea.

**Comment by chrzyki** [comment]
See https://github.com/lexibank/beidasinitic/commit/768b6b4cd47e07655cfa97908c04111dd170aff5 & note the discussion on splitting for this dataset.
